erDiagram

    MUNDIAL {
        int id PK
        int anio
        string sede
    }

    PAIS {
        int id PK
        string nombre
    }

    PARTICIPACION_MUNDIAL {
        int id PK
        int posicion_final
    }

    CLUB {
        int id PK
        string nombre
    }

    POSICION {
        int id PK
        string nombre
    }

    JUGADOR {
        int id PK
        string numero_pasaporte UK
        string nombre
        string apellido
        date fecha_nacimiento
        int numero_camiseta
    }

    ROL_TECNICO {
        int id PK
        string nombre
    }

    CUERPO_TECNICO {
        int id PK
        string numero_pasaporte UK
        string nombre
        string apellido
    }

    INSTANCIA {
        int id PK
        string nombre
    }

    PARTIDO {
        int id PK
        datetime fecha_hora
    }

    PARTICIPA_PARTIDO {
        int id PK
        string condicion
        int goles
    }

    ESTADISTICA_EQUIPO {
        int id PK
        int minutos_ataque
        int cantidad_laterales
        int cantidad_corners
    }

    TIPO_EVENTO {
        int id PK
        string nombre
    }

    EVENTO_JUGADOR {
        int id PK
        int minuto
    }


    %% ========= RELACIONES =========

    PAIS ||--o{ PARTICIPACION_MUNDIAL : participa
    MUNDIAL ||--o{ PARTICIPACION_MUNDIAL : incluye

    PAIS ||--o{ CLUB : posee

    CLUB ||--o{ JUGADOR : pertenece

    POSICION ||--o{ JUGADOR : ocupa

    PAIS ||--o{ JUGADOR : representa

    PAIS ||--o{ CUERPO_TECNICO : integra

    ROL_TECNICO ||--o{ CUERPO_TECNICO : cumple

    MUNDIAL ||--o{ PARTIDO : contiene

    INSTANCIA ||--o{ PARTIDO : corresponde

    PAIS ||--o{ PARTICIPA_PARTIDO : participa

    PARTIDO ||--o{ PARTICIPA_PARTIDO : tiene

    PARTIDO ||--o{ ESTADISTICA_EQUIPO : registra

    PAIS ||--o{ ESTADISTICA_EQUIPO : obtiene

    PARTIDO ||--o{ EVENTO_JUGADOR : ocurre

    JUGADOR ||--o{ EVENTO_JUGADOR : realiza

    TIPO_EVENTO ||--o{ EVENTO_JUGADOR : clasifica