erDiagram

    MUNDIAL {
        int id PK
        int anio
        string sede
    }

    PAIS {
        int id PK
        string nombre
    }

    PARTICIPACION_MUNDIAL {
        int id PK
        int mundial_id FK
        int pais_id FK
        int posicion_final
    }

    CLUB {
        int id PK
        string nombre
        int pais_id FK
    }

    POSICION {
        int id PK
        string nombre
    }

    JUGADOR {
        int id PK
        string numero_pasaporte
        string nombre
        string apellido
        date fecha_nacimiento
        int numero_camiseta

        int pais_id FK
        int club_id FK
        int posicion_id FK
    }

    ROL_TECNICO {
        int id PK
        string nombre
    }

    CUERPO_TECNICO {
        int id PK
        string numero_pasaporte
        string nombre
        string apellido

        int pais_id FK
        int rol_tecnico_id FK
    }

    INSTANCIA {
        int id PK
        string nombre
    }

    PARTIDO {
        int id PK
        datetime fecha_hora

        int mundial_id FK
        int instancia_id FK
    }

    PARTICIPA_PARTIDO {
        int id PK

        int partido_id FK
        int pais_id FK

        string condicion
        int goles
    }

    ESTADISTICA_EQUIPO {
        int id PK

        int partido_id FK
        int pais_id FK

        int minutos_ataque
        int cantidad_laterales
        int cantidad_corners
    }

    TIPO_EVENTO {
        int id PK
        string nombre
    }

    EVENTO_JUGADOR {
        int id PK

        int partido_id FK
        int jugador_id FK
        int tipo_evento_id FK

        int minuto
    }

    %% ===========================
    %% RELACIONES
    %% ===========================

    PAIS ||--o{ PARTICIPACION_MUNDIAL : participa
    MUNDIAL ||--o{ PARTICIPACION_MUNDIAL : incluye

    PAIS ||--o{ CLUB : posee

    CLUB ||--o{ JUGADOR : pertenece

    POSICION ||--o{ JUGADOR : ocupa

    PAIS ||--o{ JUGADOR : representa

    PAIS ||--o{ CUERPO_TECNICO : integra

    ROL_TECNICO ||--o{ CUERPO_TECNICO : cumple

    MUNDIAL ||--o{ PARTIDO : contiene

    INSTANCIA ||--o{ PARTIDO : corresponde

    PAIS ||--o{ PARTICIPA_PARTIDO : participa

    PARTIDO ||--o{ PARTICIPA_PARTIDO : tiene

    PARTIDO ||--o{ ESTADISTICA_EQUIPO : registra

    PAIS ||--o{ ESTADISTICA_EQUIPO : obtiene

    PARTIDO ||--o{ EVENTO_JUGADOR : ocurre

    JUGADOR ||--o{ EVENTO_JUGADOR : realiza

    TIPO_EVENTO ||--o{ EVENTO_JUGADOR : clasifica