# Generated by Django 6.0.6 on 2026-10-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='nombre',
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido_nombres',
            field=models.CharField(default='sin especificar', max_length=150, verbose_name='Apellido y nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='edad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipo_actual',
            field=models.CharField(default='sin especificar', max_length=100, verbose_name='Equipo actual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='pais_equipo',
            field=models.CharField(default='sin especificar', max_length=100, verbose_name='País del equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='pasaporte',
            field=models.CharField(default='sin especificar', max_length=30, unique=True, verbose_name='Número de pasaporte'),
            preserve_default=False,
        ),
    ]
