# Generated by Django 6.1.1 on 2026-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mundial',
            name='campeon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campeón'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='goles_maximo_goleador',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles del goleador'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='imagen_logo',
            field=models.ImageField(blank=True, null=True, upload_to='mundiales/logos/', verbose_name='Logo / Emblema'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='mundiales/portadas/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='maximo_goleador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Máximo Goleador'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='mejor_arquero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mejor Arquero (Guante de Oro)'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='mvp_mundial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mejor Jugador (MVP)'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='subcampeon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcampeón'),
        ),
        migrations.AddField(
            model_name='mundial',
            name='tercer_puesto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tercer Puesto'),
        ),
    ]
