# Generated by Django 6.1.1 on 2026-10-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_mundial_campeon_mundial_goles_maximo_goleador_and_more'),
        ('mundial', '0003_alter_jugador_edad_alter_jugador_numero_camiseta_and_more'),
    ]

    operations = [
    ]
